remote_theme: alshedivat/al-folio
name: Barathkrishna Satheeshkumar
description: "Robotics, Controls, and Motion Planning Researcher"
avatar: assets/img/profile_picture.jpg
content_width: 1000px

nav:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Projects"
    url: /projects/
  - title: "Experience"
    url: /experience/
  - title: "Resume"
    url: /cv/
  - title: "Contact"
    url: /contact/

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
scholar:
  no_jekyll_scholar: true
